### PR TITLE
Add scumware.org lookup

### PR DESCRIPTION
**Pull request by wesinator**

### CODE REVIEW

**Comment by ninoseki** [comment]
Hi @wesinator, thank you for your PR.
But please test your PR before submitting.

```bash
# Test for CI
npm install
npm run test

# Build the extension for testing in the browser
npm run build
```

**Comment by wesinator** [comment]
@ninoseki after https://github.com/ninoseki/mitaka/pull/313/commits/503a79b9db4751f44920f7d1a7f301e1adf23ba4 , not sure why this would be failing

**Comment by ninoseki** [comment]
Please test it in your local env before committing.
Please read build & error logs for fixing errors.

**Comment by wesinator** [comment]
> Please test it in your local env before committing.
> Please read build & error logs for fixing errors.

forgot to add to searchers index.

p.s. is there a build script to quickly add a new site ?

**Comment by ninoseki** [comment]
It still has a bug. 
Please test it in your browser before submitting.

**Comment by wesinator** [comment]
> It still has a bug.
> Please test it in your browser before submitting.

this is fixed. I forgot to add all the types

**Comment by ninoseki** [comment]
The last question is about Scumware.
Is it useful? I'm not sure the use-case of this service.

**Comment by wesinator** [comment]
> The last question is about Scumware.
> Is it useful? I'm not sure the use-case of this service.

Yes, if you scroll down on a report it gives URL , IP, and hash of malware
https://www.scumware.org/report/BB1FFA9E48599278B75F13A44363AD77
image

I wouldn't have gone through the trouble of making a PR and learning the mitaka structure if I didn't find it a useful addition.

**Comment by ninoseki** [comment]
Could you show me an example of a hash which VirusTotal doesn't have but Scumware has?
If there is no such hash, I don't think it is useful.

**Comment by wesinator** [comment]
> Could you show me an example of a hash which VirusTotal doesn't have but Scumware has?
> If there is no such hash, I don't think it is useful.

it is still useful, because it ties file hash to URL that VirusTotal might not have. 
https://www.scumware.org/report/104.168.137.213
VT has the file, but doesn't link it with the URL - https://www.virustotal.com/gui/file/8f924f8cc8457e7e77c791896e4f19ff90d79958a3cfef95b2f77fc8a521bf0c/relations 

plus, I've already done the work of adding this source. 
I added this source because I use mitaka and had a personal use for scumware.

**p.s.** regardless, this is one of the best OSINT browser extensions out there that I've used.
Thanks for building it :)

**Pull request merged**
