### PR TITLE
define content_security_policy - #464

### PR DESCRIPTION
**Pull request by juju4**
quick attempt

testing needed
to be reviewed with travis testing

### CODE REVIEW

**Comment by juju4** [comment]
travis seems ok https://travis-ci.com/github/ninoseki/mitaka/builds/184050143
comments?

**Comment by ninoseki** [comment]
Thanks but the Jest specs don't contain an E2E testing. It means you have to test the extension locally. 
I'd appreciate if you could test it locally and also provide evidences (e.g. screenshots).

**Comment by ninoseki** [comment]
Especially please make sure that you can make Cross-Origin XMLHttpRequests with the suggested CSP.

**Comment by juju4** [comment]
any specific action(s) to test that?
in general, any log to verify or just debug console?

**Comment by ninoseki** [comment]
Please share the logs of all the scan actions in the console.

**Comment by juju4** [comment]
Tested under Chromium Linux 85.0.4183.83
No real issues, details below
Where I can test cross-origin XHR? all the ones I tried for now are GET requests.

* Load Unpack
Loaded but Error:
```
Unrecognized manifest key 'browser_specific_settings'.
```
= seems code is relative to gecko/mozilla and non-blocking also not related to change AFAIK. ignored for now.
else normal

* Test on IP
working well censys, robtex, greynoise, talos, alienvault
small missing update for shodan: https://www.shodan.io/host/%s = 404. https://www.shodan.io/search?query=%s is the correct one
0 logs in chromium javascript console

* Test on domain
same crt, he, dnslytics, threatminer
viewdns: console alert
```
Uncaught ReferenceError: gtag is not defined
    at ?domain=Censys.io:136
main.js:1 Platform: studio
main.js:1 Waiting for Enabler
main.js:1 Rendering banner
```
= seems more related to upstream website than mitaka.

screenshots
Mitaka 0.77.4 https://ibb.co/jDNdLSm
Menu https://ibb.co/5F6By23
On IP https://ibb.co/5F6By23

**Comment by ninoseki** [comment]
You just made a search action. Please read the README carefully.

**Comment by juju4** [comment]
Sorry, I don't understand.
I read the README multiple times, used it as test input for context menu and validate that I see corresponding context menu for each type IP to gaTrackID.

The only extra things was testing API-based services which, yes, are using XMLHttpRequests.
added connect-src with corresponding base url.

not sure if there is more to look?

**Comment by ninoseki** [comment]
Looks good. Please test it on Chrome and also Firefox.

**Comment by ninoseki** [comment]
Oops, you should check the endpoint of each API and also please make a commit after testing.

**Comment by juju4** [comment]
Test ok with Firefox 80.0.1 and Chrome 85.0.4183.102 (Linux 64bits)
There is only 3 API based service, right? (VT, Hybrid-analysis, urlscan) Those are working fine with connect-src.

> please make a commit after testing

you mean merge in a single commit?

**Comment by ninoseki** [comment]
Please submit the evidences, please? 
(Logs of HTTP responses from the API endpoints)

**Comment by juju4** [comment]
from where?
for example, chrome shows nothing in javascript console and network tab does not seem to update when request hybrid analysis on a url.
extension settings don't present any log file link

**Comment by ninoseki** [comment]
You can check it in the console of the background script.

**Comment by juju4** [comment]
* Chrome: `Refused to set unsafe header "user-agent"` - non-blocking. seems unrelated to change
https://github.com/segmentio/analytics-node/issues/139
https://code.i-harness.com/en/q/6e060b

happens only with hybrid-analysis, not virustotal, nor urlscan
```
vendor.js:1 Refused to set unsafe header "user-agent"
(anonymous) @ vendor.js:1
l @ vendor.js:1
(anonymous) @ vendor.js:1
e.exports @ vendor.js:1
e.exports @ vendor.js:7
Promise.then (async)
c.request @ vendor.js:7
n.forEach.c.<computed> @ vendor.js:7
(anonymous) @ vendor.js:1
(anonymous) @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
scanByURL @ background.js:1
(anonymous) @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
url @ background.js:1
(anonymous) @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
scan @ background.js:1
(anonymous) @ background.js:1
a @ background.js:1
Promise.then (async)
c @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
h @ background.js:1
(anonymous) @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
(anonymous) @ background.js:1
```

This one happens if urlscan on ignore list like https://github.com
```
vendor.js:1 POST https://urlscan.io/api/v1/scan/ 400
```

* Firefox
unsafe header does not appear.
same for urlscan

**Comment by ninoseki** [comment]
I just want to confirm that the API request gets a 200 (or 20x) request.
Could you provide that information, please?

**Comment by ninoseki** [comment]
> > please make a commit after testing
> 
> you mean merge in a single commit?
Just a follow-up. You made a PR/commit without testing. It is not a good manner in general.

**Comment by ninoseki** [comment]
Finally I got time & changed my mind and test your PR. Thank you for your contribution.

Screen Shot 2020-09-25 at 9 12 32 AM

**Comment by juju4** [comment]
Thanks a lot!
pending new release to validate crxcavator score update (currently 394 with v0.78)

**Comment by juju4** [comment]
Just for note, score down to 22 on https://crxcavator.io/report/bfjbejmeoibbdpfdbmbacmefcbannnbg/0.78.1

**Pull request merged**
